### ISSUE TITLE
Redmine 4.2.1.stable support

### ISSUE THREAD

**Issue by Jiangshan00001** [pangaeatech/redmine-stuff-to-do-plugin#4]
[!] There was an error parsing `Gemfile`:
[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice coming from different sources.
You specified that rails-controller-testing (>= 0) should come from rubygems repository https://rubygems.org/ or installed locally and
. Bundler cannot continue.

 #  from /usr/src/redmine/plugins/stuff_to_do_plugin/Gemfile:6
 #  -------------------------------------------
 #  group :test do
 >    gem "rails-controller-testing"
 #    # since rails 5
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /usr/src/redmine/Gemfile:108
 #  -------------------------------------------
 #  Dir.glob File.expand_path("../plugins/*/{Gemfile,PluginGemfile}", __FILE__) do |file|
 >    eval_gemfile file
 #  end
 #  -------------------------------------------

**Comment by Jiangshan00001** [comment]
/usr/src/redmine/plugins/stuff_to_do_plugin/app/models/stuff_to_do_mailer.rb:5:in `<class:StuffToDoMailer>': undefined method `split' for nil:NilClass (NoMethodError)
        from /usr/src/redmine/plugins/stuff_to_do_plugin/app/models/stuff_to_do_mailer.rb:2:in `<top (required)>'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `require'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `block in require'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:257:in `load_dependency'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `require'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:378:in `block in require_or_load'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:37:in `block in load_interlock'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies/interlock.rb:13:in `loading'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:37:in `load_interlock'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:356:in `require_or_load'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:334:in `depend_on'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:246:in `require_dependency'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/engine.rb:477:in `each'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/engine.rb:477:in `block in eager_load!'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/engine.rb:475:in `each'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/engine.rb:475:in `eager_load!'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/engine.rb:356:in `eager_load!'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/application/finisher.rb:69:in `each'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/initializable.rb:32:in `instance_exec'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/initializable.rb:32:in `run'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /usr/local/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
        from /usr/local/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /usr/local/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /usr/local/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `each'
        from /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `call'
        from /usr/local/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
        from /usr/local/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
        from /usr/local/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/initializable.rb:60:in `run_initializers'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/application.rb:361:in `initialize!'
        from /usr/src/redmine/config/environment.rb:16:in `<top (required)>'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `require'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `block in require'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:257:in `load_dependency'
        from /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `require'
        from config.ru:3:in `block in <main>'
        from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
        from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
        from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
        from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
        from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/commands/server/server_command.rb:27:in `app'
        from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
        from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:312:in `block in start'
        from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:379:in `handle_profiling'
        from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:311:in `start'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/commands/server/server_command.rb:53:in `start'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/commands/server/server_command.rb:147:in `block in perform'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/commands/server/server_command.rb:142:in `tap'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/commands/server/server_command.rb:142:in `perform'
        from /usr/local/bundle/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/command/base.rb:69:in `perform'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/command.rb:46:in `invoke'
        from /usr/local/bundle/gems/railties-5.2.5/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'

**Comment by Jiangshan00001** [comment]
I, [2021-10-08T09:53:46.623900 #1]  INFO -- :   Rendering plugins/stuff_to_do_plugin/app/views/stuff_to_do/index.html.erb within layouts/base
I, [2021-10-08T09:53:46.629334 #1]  INFO -- :   Rendered collection of plugins/stuff_to_do_plugin/app/views/stuff_to_do/_item.html.erb [0 times] (0.0ms)
I, [2021-10-08T09:53:46.629788 #1]  INFO -- :   Rendered plugins/stuff_to_do_plugin/app/views/stuff_to_do/_left_panes.html.erb (1.7ms)
I, [2021-10-08T09:53:46.631900 #1]  INFO -- :   Rendered plugins/stuff_to_do_plugin/app/views/stuff_to_do/_issue.html.erb (1.9ms)
I, [2021-10-08T09:53:46.632422 #1]  INFO -- :   Rendered plugins/stuff_to_do_plugin/app/views/stuff_to_do/_issue.html.erb (0.4ms)
I, [2021-10-08T09:53:46.634231 #1]  INFO -- :   Rendered plugins/stuff_to_do_plugin/app/views/stuff_to_do/_issue.html.erb (1.7ms)
I, [2021-10-08T09:53:46.634269 #1]  INFO -- :   Rendered collection of plugins/stuff_to_do_plugin/app/views/stuff_to_do/_item.html.erb [3 times] (4.3ms)
I, [2021-10-08T09:53:46.634571 #1]  INFO -- :   Rendered plugins/stuff_to_do_plugin/app/views/stuff_to_do/_right_panes.html.erb (4.7ms)
I, [2021-10-08T09:53:46.634882 #1]  INFO -- :   Rendered plugins/stuff_to_do_plugin/app/views/stuff_to_do/_panes.html.erb (7.0ms)
I, [2021-10-08T09:53:46.637818 #1]  INFO -- :   Rendered plugins/stuff_to_do_plugin/app/views/stuff_to_do/_time_grid_form.html.erb (1.3ms)
I, [2021-10-08T09:53:46.638769 #1]  INFO -- :   Rendered plugins/stuff_to_do_plugin/app/views/stuff_to_do/_time_grid.html.erb (2.4ms)
I, [2021-10-08T09:53:46.638808 #1]  INFO -- :   Rendered plugins/stuff_to_do_plugin/app/views/stuff_to_do/index.html.erb within layouts/base (14.9ms)
I, [2021-10-08T09:53:46.638910 #1]  INFO -- : Completed 500 Internal Server Error in 29ms (ActiveRecord: 6.9ms)
F, [2021-10-08T09:53:46.639489 #1] FATAL -- :
F, [2021-10-08T09:53:46.639504 #1] FATAL -- : ActionView::Template::Error (The `content_tag_for` method has been removed from Rails. To continue using it, add the `record_tag_helper` gem to your Gemfile:
  gem 'record_tag_helper', '~> 1.0'
Consult the Rails upgrade guide for details.):
F, [2021-10-08T09:53:46.639583 #1] FATAL -- :     28:   </thead>
    29:   <tbody>
    30:     <% @spent_issues.each do |issue| %>
    31:     <%= content_tag_for(:tr, issue) do %>
    32:       <td class="time-grid-project">
    33:         <%= link_to(h(issue.project), controller: 'projects', action: 'show', id: issue.project) %>
    34:       </td>
F, [2021-10-08T09:53:46.639593 #1] FATAL -- :
F, [2021-10-08T09:53:46.639601 #1] FATAL -- : plugins/stuff_to_do_plugin/app/views/stuff_to_do/_time_grid.html.erb:31:in `block in _plugins_stuff_to_do_plugin_app_views_stuff_to_do__time_grid_html_erb___88         5060068689808966_160780'
plugins/stuff_to_do_plugin/app/views/stuff_to_do/_time_grid.html.erb:30:in `each'
plugins/stuff_to_do_plugin/app/views/stuff_to_do/_time_grid.html.erb:30:in `_plugins_stuff_to_do_plugin_app_views_stuff_to_do__time_grid_html_erb___885060068689808966_160780'
plugins/redmine_workflow_enhancements/lib/workflow_enhancements/patches/action_view_rendering.rb:53:in `render_with_workflow_enhancements'
plugins/stuff_to_do_plugin/app/views/stuff_to_do/index.html.erb:71:in `_plugins_stuff_to_do_plugin_app_views_stuff_to_do_index_html_erb___3254574102653606879_119300'
plugins/stuff_to_do_plugin/app/controllers/stuff_to_do_controller.rb:22:in `block (2 levels) in index'
plugins/stuff_to_do_plugin/app/controllers/stuff_to_do_controller.rb:21:in `index'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:56:in `call'
I, [2021-10-08T09:53:57.154072 #1]  INFO -- : Started GET "/issues/174" for 112.232.171.48 at 2021-10-08 09:53:57 +0000
I, [2021-10-08T09:53:57.154826 #1]  INFO -- : Processing by IssuesController#show as HTML
I, [2021-10-08T09:53:57.154856 #1]  INFO -- :   Parameters: {"id"=>"174"}
I, [2021-10-08T09:53:57.159965 #1]  INFO -- :   Current user: wwwtwewts (id=6)
I, [2021-10-08T09:53:57.215609 #1]  INFO -- :   Rendering issues/show.html.erb within layouts/base
I, [2021-10-08T09:53:57.217243 #1]  INFO -- :   Rendered issues/_action_menu.html.erb (1.4ms)

**Comment by Jiangshan00001** [comment]
#5

**Comment by mwaddell** [comment]
I'm currently using Redmine 4.2.1-stable with the stuff-to-do plugin and have not seen the Bundler issue you reported.  I do see issues with the time grid not working, but your PR does not appear to fix those issues for me.

![image](https://user-images.githubusercontent.com/750244/136851325-34a994cf-e6a7-469c-b83a-8c8a2b8f4b71.png)

**Comment by Jiangshan00001** [comment]
@mwaddell 
1. the Bundler issue maybe a conflit with other plugin.
2. i meet two issues with the time_grid.
2.1.  first is that I could only commit the time_entry once, and then the right menu could not appear any more.  this is fixed i think.
2.2. after press next pager or prev pager, could not select the grid and  add  time_entry  any more.  this is changed to: 
      after press next pager or prev pager, ths select is not shown, but you could add time_entry as right-menu could show.
